language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam-start

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.03 OCAML_RELEASE=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.06 OCAML_RELEASE=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.07 OCAML_RELEASE=0
    stage: Build
